# Generated by Django 3.2 on 2022-11-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='person_data',
        ),
    ]
