# Generated by Django 3.2 on 2022-11-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_passport_person_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='passport',
            name='id_card',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vipclient',
            name='donation_amount',
            field=models.IntegerField(),
        ),
    ]
