# Generated by Django 3.2 on 2022-11-14 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20221114_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='person_data',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
            preserve_default=False,
        ),
    ]
